### PR TITLE
Declare used dependencies

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by gnodet** [comment]
Should we enable `maven-dependency-analyzer` with `failOnUnusedDeclaredDependencies` and `failOnWarning`
 in some parent ?

**Comment by elharo** [comment]
Probably not yet. That would break a lot of other plugins that haven't been cleaned up yet.

**Comment by gnodet** [comment]
> Probably not yet. That would break a lot of other plugins that haven't been cleaned up yet.

That would break plugins _only_ when upgrading the parent.  The exact point is to enforce new plugin releases to have clean dependencies.  Anyway, not a big deal...

**Comment by elharo** [comment]
Yes, that's true. It's still a lot of extra work to do before updating the parent, which might need to be done quickly for unrelated reasons.

**Comment by gnodet** [comment]
> Yes, that's true. It's still a lot of extra work to do before updating the parent, which might need to be done quickly for unrelated reasons.

Given the `m-dependency-p`'s analyze goal knows about direct dependencies, why don't we have a goal to automatically fix these dependencies, i.e. remove unused ones and add undeclared ones.  Even if that's not perfect, it could still be tuned by the user, but it would remove a big part of the tedious work.

**Review by slawekjaranowski — APPROVED** [review]

**Pull request merged**
