### PR TITLE
[MSHARED-955] make parseOutputTimestamp static

### PR DESCRIPTION
**Pull request by elharo**
@hboutemy  @mabrarov

### CODE REVIEW

**Comment by pzygielo** [comment]
It is `IncompatibleClassChange` (https://github.com/apache/maven-ear-plugin/pull/10#discussion_r481249976).

**Comment by mabrarov** [comment]
@pzygielo, sorry for a stupid question, but does it make sense if this change will be released with new version of Maven Archiver? Isn't it sufficient to notify users of this library about this incompatible class change in release notes so that they will become aware of it when migrating to the new version of Maven Archiver?

**Comment by pzygielo** [comment]
> Isn't it sufficient to notify users of this library about this incompatible class change 

Maybe it is sufficient, but one has to be aware of that to prepare notification.

**Comment by elharo** [comment]
I think the issue only appears if a subclass overrides this method.

**Comment by pzygielo** [comment]
> I think the issue only appears if a subclass overrides this method.

If so changed class appears in place of old one - without recompiling client - then `IncompatibleClassChangeError` would be raised.<sup>1</sup> Thus it depends how maven-archiver artifact is used.

1. I imagine overriding maven-jar/ear-plugin dependency to use new release of maven-archiver for example.

**Comment by elharo** [comment]
@pzygielo can you provide more details on what code would be required to trigger this?

**Comment by mabrarov** [comment]
To be honest implementation of `parseOutputTimestamp` looks wrong because it doesn't parse optional time zone. This causes issues with `project.build.outputTimestamp` maven property having values like `2020-05-01T12:12:12Z`. It's a separate issue but may be we could combine changes into a single pull request.

**Comment by pzygielo** [comment]
> @pzygielo can you provide more details on what code would be required to trigger this?

See https://github.com/pzrep/MSHARED-955

**Comment by elharo** [comment]
Thanks. That's not something I'm worried about happening in practice. Is there a likely diamond dependency problem where the incompatible version gets selected?

**Comment by pzygielo** [comment]
> That's not something I'm worried about happening in practice. 

I know. But I do.

So I've updated my example for the case, where this dependency is overriden in assembly plugin (i.e. archiver is no longer direct dependency of code in my example, but is utilized by plugin).

Per http://maven.apache.org/plugins/maven-assembly-plugin/dependencies.html assembly plugin uses archiver in version 3.5.0 (the latest).

Per https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_dependencies_Tag:
> You could configure the dependencies of the Build plugins, commonly to use a more recent dependency 
> version.

So I do in my example, pretending that 3.5.1-SNAPSHOT is released now and I like other changes in it, and there is no better release of assembly plugin. Example shows that proposed change is not backward compatible.

---
I'm only saying, that if there is no other way - it shall be reflected in version of plugin, as per https://semver.org/, which might not be observed here but is kind of standard:
> increment MAJOR version when you make incompatible API changes,

or **at least** as @mabrarov said - very clearly stated in RN.

**Comment by rfscholte** [comment]
For the record: Maven doesn't really understand semver, it is just a hint. If for the same groupId+artifactId a version 1.0 and 3.1 are in the dependency graph, Maven will pick only 1 based on the "nearest wins"-rule. Marking breaking changes with the versions might work for frameworks like spring, but not for libraries like commons-lang. Hence they made the right decision to change both artifactId and the package to prevent collisions.

**Comment by mabrarov** [comment]
Is this PR still actual?

**Comment by michael-o** [comment]
Likely, @hboutemy WDYT?

**Comment by jira-importer** [comment]
Resolve #205

**Pull request closed without merging**
